spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/s1db
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      use-new-id-generator-mappings: false #spring 2 ?? ????? identity ??? ??????
      ddl-auto: create
    database: h2
    show-sql: true
    properties:
      hibernate.format_sql: true
  redis:
    port: 6379
    host: localhost

timeout: 86400
secret: abcabcabcabcabcabcabcabcabcabcab
  #sha256을 이용할거니 키 길이 최소 >= 256bit 32byte